### PR TITLE
LanguageManager

### PR DESCRIPTION
**Pull request by NickolasFleim**
I made it possible to make translations.
(P.S. Second attempt. Rewritten in xml)
(P.S.S. I somehow messed up the whitespaces in AdvancedCauseOfDeath.cs and I don’t know how to fix it)

### CODE REVIEW

**Comment by NickolasFleim** [comment]
P.S.S.S You can use "Hide whitespaces" in settings to better look

**Comment by EliteMasterEric** [comment]
Thank you very much for your contribution! I will be reviewing it more thoroughly soon.

**Comment by EliteMasterEric** [comment]
I will be looking into potentially refactoring this somewhat to make it more dynamic, however when I do that I will still make sure that the PR registers as "merged" and your name ends up in the README. This is a very useful feature you've contributed, and giving credit where it's due is very important.

**Comment by NickolasFleim** [comment]
A little messy, but with a dynamic system)))

**Comment by NickolasFleim** [comment]
P.S. I don't know if this will sync between players

**Comment by EliteMasterEric** [comment]
Just looked over the changes you made, this is very nice! I will definitely look into working on this later.

> P.S. I don't know if this will sync between players

The way this is written now, the messages should sync between players IF they are using the same language AND their configs are the same. If the user has overridden their language file in a way that adds or removes death messages, it obviously won't be synced anymore, but alternate configs can be provided via modpacks so it's easy to get multiple people to use the same modified setup.

Also, I noticed the Russian translation uses special characters that the IBM3270 font doesn't seem to support, do you have a screenshot of the mod working in-game?

**Comment by NickolasFleim** [comment]
With this mod https://thunderstore.io/c/lethal-company/p/Hayrizan/russian_textures/ the font is nice (but sometimes squares appear instead of symbols). In this mod, the font is replaced somewhere in the game itself.
Without this mod, the text in Russian becomes black.

**Comment by NickolasFleim** [comment]
<details>

<summary>Without mod</summary>

[![Without mod][1]][1]
 
[1]: https://github.com/EliteMasterEric/Coroner/assets/2946000/9df67669-2a43-49a2-a511-cb332a7fa380
 
</details>

<details>

<summary>With mod</summary>

[![With mod][2]][2]
 
[2]: https://github.com/EliteMasterEric/Coroner/assets/2946000/ae8776ee-a714-4b3f-a3c7-5e7fe0981383
 
</details>

**Pull request merged**
