### PR TITLE
Add messages from MoreDeathNotes and some new ones

### PR DESCRIPTION
**Pull request by TheBlackEntity**
Didn't want to add one more fork to the 50 quadrillion ones that already exist, so I'm hoping this is getting merged...

I took the time to add all messages from MoreDeathNotes into the language string file.

I also added a few of my own messages

### CODE REVIEW

**Comment by TheBlackEntity** [comment]
Oh... I just realized that I haven't tested the messages yet, so some of them might be too long, actually...

Going to test them and report back.

Sorry for the inconvenience

**Comment by TheBlackEntity** [comment]
So I either go the worst luck imaginable (Which I got anyway...) or something causes most of the notes to never appear.

More notes are awesome, but it's pretty bad, if they never get picked...


I can understand it, if you don't want to bother fixing this just to be able to merge this

**Comment by TheBlackEntity** [comment]
Nevermind! I was stupid enough to accidentally install MoreDeathNotes alongside Coroner...

Everything seems to work just fine

**Comment by EliteMasterEric** [comment]
Oh yeah I saw this earlier but forgot to review it, my response:

Absolute garbage AI-generated slop. The messages that are even the slightest smidgen tangential to the actual game (I haven't played very much v50 but I'm pretty sure there are NO GRIZZLY BEARS) are absolutely bland and possess no creative merit.

Don't come back to this repo unless you have something of real value to contribute.

**Pull request closed without merging**
